version: "3"

services:
  test-net:
    image: docker.io/goforbroke1006/ethereum:latest
    command:
      - --syncmode=light
      - --goerli # connect to test network, allowed or --rinkeby or --goerli or --sepolia
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.corsdomain=*
      - --http.api=personal,eth,net,web3
    ports:
      - "8545:8545"
