version: "3"

services:
  test-net:
    image: docker.io/goforbroke1006/ethereum:latest
    ports: [ "8545:8545" ]
    volumes:
      - ./.docker-compose/test-net/root/.ethereum/:/root/.ethereum:rw
      - ./.docker-compose/test-net/data/:/data/:rw
